name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ถ้าคุณมีสคริปต์สร้าง manifest ให้รันที่นี่ด้วย เช่น:
      # - run: npm ci && npm run manifest
      - name: Upload public dir
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
